name: hifi_mamba
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pytorch=1.13.1
  - torchvision=0.14.1
  - pytorch-cuda=11.7
  - numpy
  - scipy
  - scikit-image
  - h5py
  - pyyaml
  - yacs
  - tqdm
  - pip:
      - einops
      - timm
      - fvcore
      - tensorboardX
      - pytorch-wavelets
